baseurl = "/"
title = "HOME : 0script"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Welcome to 0script blog."
    description = "My journey into computer  articles in french and english."
    github = "https://github.com/0script"
    twitter = "https://twitter.com/XXX"
    email = "z5r00script@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"