baseurl = "/"
title = "Blog : 0script"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Deep dive into computer science with 0script"
    description = "Hello Friend , this is 0script blog to help you in your tech journey . Here are my articles by publication date."
    github = "https://github.com/0script"
    twitter = "https://twitter.com/XXX"
    linkedin = "https://www.linkedin.com/in/marcel-levy-nkoghe-obame-4479091a6/"
    email = "z5r00script@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"
    name = "0scriptblog"

[Permalinks]
    post = "/:filename/"

[menu]
[[menu.main]]
  identifier = 'contact'
  name = 'contact us'
  url = '/contact/'
[[menu.main]]
  identifier = 'home'
  name = 'home'
  url = '/'
[[menu.main]]
  identifier = 'about'
  name = 'about 0script'
  url = '/about-me/'